# Generated by Django 4.2.6 on 2023-10-27 08:45

import core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'entreprise")),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name="Adresse de l'entreprise")),
                ('phone_number', models.CharField(max_length=255, verbose_name="Téléphone de l'entreprise")),
                ('logo', models.ImageField(blank=True, null=True, upload_to='uploads/enterprise_logo', validators=[core.validators.validate_image_size, core.validators.validate_image_extension], verbose_name="Logo de l'entreprise")),
                ('web_site', models.CharField(blank=True, max_length=255, null=True, verbose_name="Site web de l'entreprise")),
                ('description', models.TextField(verbose_name="Description de l'entreprise")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date de création de l'entreprise")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="Date de modification de l'entreprise")),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Offer name')),
                ('name_language_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Offer name language key')),
                ('description', models.TextField(verbose_name='Offer description')),
                ('description_language_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Offer description language key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Offer created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Offer modified at')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Subscription name')),
                ('language_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subscription language key')),
                ('price', models.FloatField(verbose_name='Subscription price')),
                ('duration', models.IntegerField(verbose_name='Subscription duration in days')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False, verbose_name='User subscription is active')),
                ('subcription_date', models.DateTimeField(auto_now_add=True, verbose_name='User subscription date')),
                ('expiration_date', models.DateTimeField(verbose_name='User subscription expiration date')),
                ('payment_method', models.CharField(max_length=255, verbose_name='User subscription payment method')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='User subscription created at')),
                ('reference', models.CharField(max_length=255, verbose_name='User subscription reference')),
                ('subcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_of_user', to='account.subscription', verbose_name='User subcription')),
            ],
        ),
    ]
