# Generated by Django 4.2.6 on 2023-10-19 20:42

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/enterprise_logo', validators=[core.validators.validate_image_size, core.validators.validate_image_extension], verbose_name="Logo de l'entreprise"),
        ),
    ]
