# Generated by Django 4.2.6 on 2023-10-31 23:45

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nom du magasin')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse du magasin')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Téléphone du magasin')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='uploads/enterprise_logo', validators=[core.validators.validate_image_size, core.validators.validate_image_extension], verbose_name='Logo du magasin')),
                ('description', models.TextField(verbose_name='Description du magasin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création du magasin')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification du magasin')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_country', to='cities_light.country', verbose_name='Pays du magasin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_user', to=settings.AUTH_USER_MODEL, verbose_name='User store')),
            ],
            options={
                'verbose_name': 'Magasin',
                'verbose_name_plural': 'Magasins',
            },
        ),
    ]
