# Generated by Django 4.2.6 on 2023-10-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_entreprise_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='description_language_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Offer description language key'),
        ),
        migrations.AddField(
            model_name='offer',
            name='name_language_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Offer name language key'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='language_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subscription language key'),
        ),
    ]
