# Generated by Django 4.2.6 on 2023-11-01 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='country',
        ),
    ]
