# Generated by Django 4.2.6 on 2023-10-27 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_initial'),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('authentication', '0001_initial'),
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerdelivery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_delivery_user', to=settings.AUTH_USER_MODEL, verbose_name='Seller delivery user'),
        ),
        migrations.AddField(
            model_name='productssection',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='product_category_section', to='settings.productcategory', verbose_name='Product product category'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_order_delivery_address', to='authentication.userdeliveryaddress', verbose_name='Product order delivery address'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='delivery_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order_delivery_method', to='settings.deliverymethod', verbose_name='Product order delivery method'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order_payment_method', to='settings.paymentmethod', verbose_name='Product order payment method'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_order_product', to='advert.product', verbose_name='Product order product'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_order_seller', to=settings.AUTH_USER_MODEL, verbose_name='Product order seller'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order_user', to=settings.AUTH_USER_MODEL, verbose_name='Product order user'),
        ),
        migrations.AddField(
            model_name='productfavorite',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_favorite_product', to='advert.product', verbose_name='Product favorite product'),
        ),
        migrations.AddField(
            model_name='productfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_favorite_user', to=settings.AUTH_USER_MODEL, verbose_name='Product favorite user'),
        ),
        migrations.AddField(
            model_name='productcomment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comment_product', to='advert.product', verbose_name='Product comment product'),
        ),
        migrations.AddField(
            model_name='productcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comment_user', to=settings.AUTH_USER_MODEL, verbose_name='Product comment user'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='settings.productcategory', verbose_name='Product product category'),
        ),
        migrations.AddField(
            model_name='product',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_seller_entreprise', to='account.entreprise', verbose_name='Product seller entreprise'),
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='product_images', to='advert.productimage', verbose_name='Product images'),
        ),
        migrations.AddField(
            model_name='product',
            name='made_in',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.country', verbose_name='Product made in'),
        ),
        migrations.AddField(
            model_name='product',
            name='measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.measure', verbose_name='Product measure'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_seller_user', to=settings.AUTH_USER_MODEL, verbose_name='Product seller user'),
        ),
    ]
