# Generated by Django 4.2.6 on 2023-10-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(related_name='product_images', to='advert.productimage', verbose_name='Product images'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Is main product image'),
        ),
    ]
