# Generated by Django 4.2.6 on 2023-10-27 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerdelivery',
            name='product',
        ),
    ]
