# Generated by Django 4.2.6 on 2023-10-31 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('advert', '0003_remove_sellerdelivery_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerdelivery',
            name='delivery_method',
        ),
        migrations.AddField(
            model_name='sellerdelivery',
            name='delivery_price',
            field=models.IntegerField(default=0, verbose_name='Seller delivery delivery price'),
        ),
        migrations.AddField(
            model_name='sellerdelivery',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Seller delivery name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='made_in',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.city', verbose_name='Product made in'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('PUBLISH', 'Publié'), ('UNPUBLISH', 'Non publié'), ('WAIT', 'En attente'), ('REFUSED', 'Refusé')], default='PUBLISH', max_length=255, verbose_name='Product status'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='delivery_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_order_delivery_method', to='advert.sellerdelivery', verbose_name='Product order delivery method'),
        ),
    ]
