# Generated by Django 4.2.6 on 2023-10-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0003_product_images_productimage_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='product_images', to='advert.productimage', verbose_name='Product images'),
        ),
        migrations.DeleteModel(
            name='ProductCart',
        ),
    ]
