# Generated by Django 4.2.6 on 2023-10-19 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0004_remove_productimage_product_alter_product_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='manufacturer',
        ),
    ]
