# Generated by Django 4.2.6 on 2023-10-31 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0004_remove_sellerdelivery_delivery_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerdelivery',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
