# Generated by Django 4.2.6 on 2023-10-19 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0005_remove_product_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='delivery_time',
        ),
        migrations.AlterField(
            model_name='productorder',
            name='delivery_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order_delivery_method', to='advert.sellerdelivery', verbose_name='Product order delivery method'),
        ),
    ]
