# Generated by Django 4.2.6 on 2023-10-31 23:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0005_alter_sellerdelivery_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerdelivery',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
