# Generated by Django 4.2.6 on 2023-10-19 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0007_alter_productimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='seller',
        ),
    ]
