# Generated by Django 4.2.6 on 2023-10-19 21:25

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0008_rename_user_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='uploads/product_images', validators=[core.validators.validate_image_size, core.validators.validate_image_extension], verbose_name='Product image'),
        ),
    ]
