# Generated by Django 4.2.6 on 2023-11-01 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0009_remove_product_entreprise_product_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='sellerdelivery',
            name='user',
        ),
    ]
