# Generated by Django 4.2.6 on 2023-10-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_alter_productcategory_slug'),
        ('advert', '0009_alter_productimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionProduits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la section')),
                ('description', models.TextField(verbose_name='Description de la section')),
                ('product_type', models.CharField(choices=[('ALL_PRODUCTS', 'Tous les produits'), ('NEW_ADDED_PRODUCTS', 'Nouveaux produits ajoutés'), ('MOST_SELLING_PRODUCTS', 'Produits les plus vendus')], default='ALL_PRODUCTS', max_length=255, verbose_name='Product type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Section created at')),
                ('categories', models.ManyToManyField(blank=True, related_name='product_category_section', to='settings.productcategory', verbose_name='Product product category')),
            ],
        ),
    ]
