# Generated by Django 4.2.6 on 2023-10-25 22:45

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_alter_productcategory_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advert', '0010_sectionproduits'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Product cart created at')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Product order item quantity')),
                ('unit_price', models.FloatField(verbose_name='Product order item unit price')),
                ('total_price', models.FloatField(verbose_name='Product order item total price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Product order item created at')),
            ],
            options={
                'verbose_name': 'Product order item',
                'verbose_name_plural': 'Product order items',
            },
        ),
        migrations.CreateModel(
            name='ProductsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la section')),
                ('description', models.TextField(verbose_name='Description de la section')),
                ('product_type', models.CharField(choices=[('ALL_PRODUCTS', 'Tous les produits'), ('NEW_ADDED_PRODUCTS', 'Nouveaux produits ajoutés')], default='ALL_PRODUCTS', max_length=255, verbose_name='Product type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Section created at')),
                ('categories', models.ManyToManyField(blank=True, related_name='product_category_section', to='settings.productcategory', verbose_name='Product product category')),
            ],
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Product short description'),
        ),
        migrations.AddField(
            model_name='productcomment',
            name='rating',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Product comment rating'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Product description'),
        ),
        migrations.AlterField(
            model_name='productorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('RECEIVED', 'Reçu'), ('DELIVERED', 'Livré'), ('CANCELED', 'Annulé')], default='PENDING', max_length=255, verbose_name='Product order status'),
        ),
        migrations.DeleteModel(
            name='SectionProduits',
        ),
        migrations.AddField(
            model_name='productorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order_item_product', to='advert.product', verbose_name='Product order item product'),
        ),
        migrations.AddField(
            model_name='productcart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_cart_product', to='advert.product', verbose_name='Product cart product'),
        ),
        migrations.AddField(
            model_name='productcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_cart_user', to=settings.AUTH_USER_MODEL, verbose_name='Product cart user'),
        ),
        migrations.AddField(
            model_name='productorder',
            name='product_items',
            field=models.ManyToManyField(related_name='product_order_product_items', to='advert.productorderitem', verbose_name='Product order product items'),
        ),
    ]
