# Generated by Django 4.2.6 on 2023-11-01 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_store_country'),
        ('advert', '0010_remove_productorder_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_order_store', to='account.store', verbose_name='Product order store'),
        ),
        migrations.AddField(
            model_name='sellerdelivery',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_delivery_user', to='account.store', verbose_name='Seller delivery user'),
        ),
    ]
