# Generated by Django 4.2.6 on 2023-11-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0011_productorder_store_sellerdelivery_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('RECEIVED', 'Reçu'), ('DELIVERED', 'Livré'), ('CANCELED', 'Annulé'), ('READY_TO_BE_DELIVERED', 'Prêt à être livré')], default='PENDING', max_length=255, verbose_name='Product order status'),
        ),
    ]
