# Generated by Django 4.2.6 on 2023-10-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0011_productcart_productorderitem_productssection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('PUBLISH', 'Publié'), ('UNPUBLISH', 'Non publié'), ('WAIT', 'En attente'), ('REFUSED', 'Refusé')], default='UNPUBLISH', max_length=255, verbose_name='Product status'),
        ),
    ]
