# Generated by Django 4.2.6 on 2023-11-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0013_alter_productorder_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('PUBLISH', 'Publié'), ('UNPUBLISH', 'Non publié'), ('WAIT', 'En attente'), ('REFUSED', 'Refusé'), ('ARCHIVED', 'Archivé')], default='PUBLISH', max_length=255, verbose_name='Product status'),
        ),
    ]
