# Generated by Django 4.2.6 on 2023-10-26 01:24

import ckeditor.fields
import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='uploads/news_images', validators=[core.validators.validate_image_size, core.validators.validate_image_extension])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newstype')),
            ],
        ),
    ]
