# Generated by Django 4.2.6 on 2023-10-26 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Delivery method name')),
                ('language_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Delivery method language key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Delivery method created at')),
            ],
            options={
                'verbose_name': 'Delivery method',
                'verbose_name_plural': 'Delivery methods',
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Measure name')),
                ('short_name', models.CharField(max_length=255, verbose_name='Measure short name')),
                ('language_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Measure language key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Measure created at')),
            ],
            options={
                'verbose_name': 'Measure',
                'verbose_name_plural': 'Measures',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Payment method name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='uploads/payment_method_images', verbose_name='Payment method logo')),
                ('language_key', models.CharField(max_length=255, null=True, verbose_name='Payment method language key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Payment method created at')),
            ],
            options={
                'verbose_name': 'Payment method',
                'verbose_name_plural': 'Payment methods',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product category name')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Product category slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/product_categories', verbose_name='Product category image')),
                ('language_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Product category language key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Product category created at')),
            ],
            options={
                'verbose_name': 'Product category',
                'verbose_name_plural': 'Product categories',
            },
        ),
        migrations.CreateModel(
            name='Sectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Sector name')),
                ('language_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sectors language key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sector created at')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
            },
        ),
    ]
