# Generated by Django 4.2.6 on 2023-10-31 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0004_remove_sellerdelivery_delivery_method_and_more'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryMethod',
        ),
    ]
