# Generated by Django 4.2.6 on 2023-10-19 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_deliverymethod_delivery_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverymethod',
            name='delivery_time',
        ),
    ]
