# Generated by Django 4.2.6 on 2023-10-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_remove_deliverymethod_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymethod',
            name='language_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Delivery method language key'),
        ),
        migrations.AddField(
            model_name='measure',
            name='language_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Measure language key'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='language_key',
            field=models.CharField(max_length=255, null=True, verbose_name='Payment method language key'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='language_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Product category language key'),
        ),
        migrations.AddField(
            model_name='sectors',
            name='language_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sectors language key'),
        ),
    ]
