# Generated by Django 4.2.6 on 2023-10-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_paymentmethod_logo_productcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='Product category slug'),
        ),
    ]
