# Generated by Django 4.2.6 on 2023-10-12 21:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HOTPDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, help_text='A hex-encoded secret key of up to 40 bytes.', max_length=80, validators=[django.core.validators.MinLengthValidator(40)])),
                ('counter', models.BigIntegerField(blank=True, default=0, help_text='The counter value of the latest verified token. The next token must be at a higher counter value.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
