# Generated by Django 4.2.6 on 2023-10-31 23:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdeliveryaddress',
            name='is_main',
        ),
        migrations.AlterField(
            model_name='userdeliveryaddress',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
