# Generated by Django 4.2.6 on 2023-10-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_hotpdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profil_type',
            field=models.CharField(choices=[('USER', 'Utilisateur'), ('AGRIPRENEUR', 'Agripreneur'), ('MERCHANT', 'Commerçant')], default='USER', max_length=255, verbose_name='Profil type'),
        ),
    ]
