# Generated by Django 4.2.6 on 2023-11-01 11:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userdeliveryaddress_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastgroup',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
