# Generated by Django 4.2.6 on 2023-10-19 20:42

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_profil_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/user_images', validators=[core.validators.validate_image_size, core.validators.validate_image_extension], verbose_name='Photo de profil'),
        ),
    ]
