# Generated by Django 4.2.6 on 2023-10-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type_user', models.CharField(choices=[('USER', 'Utilisateur'), ('AGRIPRENEUR', 'Agripreneur'), ('MERCHANT', 'Commerçant')], default='USER', max_length=255, verbose_name='Profil type')),
                ('is_entreprise', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
